### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by vmazet** [emilebres/react-virtualized-checkbox#1]
I didn't know were to put this, but this doesn't work for me,

In first place I try just 
<   VirtualizedCheckbox
   items={this.state.myItems}
   hasButtons={false}
   onChange={this.mySomethink}
/>

and this doesn't work, after that I see all your props are required, so I change to:

<VirtualizedCheckbox
         items={this.state.myItems}
         labelKey={"label"}
         valueKey={"value"}
         rowHeight={30}
         onChange={this.markerCheck}
         onCancel={console.log("cancel")}
         onOk={console.log("OK")}
/>

and got the two time in my console this

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at http://localhost:3000/static/js/bundle.js:76894:30
    at Array.map (native)
    at VirtualizedCheckbox.applyTextFilter (http://localhost:3000/static/js/bundle.js:76893:34)
    at new VirtualizedCheckbox (http://localhost:3000/static/js/bundle.js:76787:24)
    at http://localhost:3000/static/js/bundle.js:26081:19
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:25861:13)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:3000/static/js/bundle.js:26080:17)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:3000/static/js/bundle.js:26066:22)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/static/js/bundle.js:25974:22)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:18425:36)

I try a last time with the items array from your simple example and this time console say items was never used,

any advice? Thanks! (sorry for my bad english)

EDIT:

I just try your simple example
list of items isn't display

**Comment by emilebres** [comment]
Hey,
Sorry for the late answer, I was out of office the last few days. 
The `toLowerCase` error usually happens when you have set the wrong `labelKey` or when one item in `items` has no label.
Can you check that?
Also it will be easier for me to help you if you give me which version of `react-virtualized-checkbox` you're using.
Cheers

**Comment by vmazet** [comment]
Hey, sorry for the late answer too !
I use the version 2.0.3 of react-virtualize-checbox,

I was trying with your items from your sample example:
const items = [
      { label: "One", value: 1 },
      { label: "Two", value: 2 },
      { label: "Three", value: 3 }
      // And so on...
    ] ,  

but empty list in the end.

finally i wrote myself a piece of code for the same result, but it was for prevent you if it's not only a bug who appear for me!

**Comment by emilebres** [comment]
I am not sure what caused the problem on your side. But some props were wrongly required. I changed that and push to npm (version 2.1.2).
I'm going to close this issue but I will still see the messages. Feel free to reopen if you still have this problem.
